### PR TITLE
Migration to Factory Bot

### PR DESCRIPTION
**Pull request by kalashnikovisme**
NOTE: had to remove `*gemfile.lock` because of travis errors.

### CODE REVIEW

**Comment by melekes** [comment]
Thank you for the PR! And for using this gem 👍

**Comment by kalashnikovisme** [comment]
@melekes what do you think about renaming to `factory_bot_sequences`?

**Comment by melekes** [comment]
I don't care. But renaming is a hassle :(

**Comment by kalashnikovisme** [comment]
FactoryGirl maintainers don't think so :)
Ok, I think, renaming is not really important for now

**Pull request merged**
